apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-anvil
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-anvil
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-anvil
    spec:
      containers:
      - name: anvil
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["anvil", "--host", "0.0.0.0", "--chain-id", "8453"]
        ports:
        - containerPort: {{ .Values.service.port }}
